### ISSUE TITLE
Some links

### ISSUE THREAD

**Issue by evantahler** [davidjairala/video-games-dornch#1]
Sorry I missed your dornch! It looked awesome!

If you give this presentation again, here are some links on the topic of "browser-based sprite games" that  I keep around:
- http://impactjs.com/
  - the best 2-d sprite based layout engine ever (browser) (I've got a license if you want to try it)
- http://qiao.github.io/PathFinding.js/visual/
  - a visual representation of many pathfinding algorithms in the browser
- http://jlongster.com/Making-Sprite-based-Games-with-Canvas
  - tips on canvas redraw loops vs game loops (in the browser)

**Comment by davidjairala** [comment]
Thanks for the links buddy!  Added them to the [readme](https://github.com/davidjairala/video-games-dornch/blob/master/README.md#interesting-links).

**Comment by evantahler** [comment]
now I want to make a video game...

**Comment by davidjairala** [comment]
I've got this old one from around 2011 that I never finished:
http://chickengames.tumblr.com/

We should port it to Javascript and finish it up!

On Wed, Mar 25, 2015 at 10:14 AM, Evan Tahler notifications@github.com
wrote:

> now I want to make a video game...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/davidjairala/video-games-dornch/issues/1#issuecomment-86126660
> .

## 

David Jairala
davidjairala@gmail.com

**Comment by evantahler** [comment]
Ha! I just checked on an old canvas game (in ejecta/impact) from ~ 2years ago and it doesn't even come close to working with today's fancy modern browser

![screen shot 2015-03-25 at 5 19 12 pm](https://cloud.githubusercontent.com/assets/303226/6830660/342a1330-d313-11e4-8880-10c4a1a08b56.png)
